### ISSUE TITLE
After windows update the software does not working

### ISSUE THREAD

**Issue by Varga-Levente** [omriharel/deej#129]
```
2024-11-30 01:52:03.609 DEBUG   deej.tray                       Running in tray
2024-11-30 01:52:03.632 DEBUG   deej.tray                       Tray instance ready
2024-11-30 01:52:03.666 INFO    deej                            Run loop starting
2024-11-30 01:52:03.666 DEBUG   deej.serial                     Attempting serial connection    {"comPort": "COM3", "baudRate": 9600, "minReadSize": 0}
2024-11-30 01:52:03.666 DEBUG   deej.config                     Starting to watch user config file for changes  {"path": "config.yaml"}
2024-11-30 01:52:03.674 INFO    deej.serial.com3                Connected       {"conn": {}}
```
**It not recognises the sliders.
Can anyone help? Anyone has a fix?**

**Comment by andrehen** [comment]
I have exactly the same problem...  I'm using Windows 10 22H2. Tested the serial communication and the values are being received normally.

**Comment by andrehen** [comment]
@Varga-Levente Just found out that this is exactly the same issue as https://github.com/omriharel/deej/issues/127. My CH340 driver was 3.9.2024.9, reverting it solved the problem! It is now version 3.5.2019.1.

**Comment by satsukiyatoshi** [comment]
> 3.5.2019.1

same issue after 23h2 udpate, fixed with this driver version, thanks !
https://www.visualmicro.com/page/CH340-Driver-Fix-Installation.aspx issue explained + good driver vesion

**Comment by Varga-Levente** [comment]
So a day later I turned on the computer and it worked again without me doing anything. 🤔🤔🤔

**Comment by CardinalFangIsHere** [comment]
The old driver does not fix it for me, I can't start the application, it immediately closes.
EDIT: my issue was caused by a change in COM port. Finally found the log and saw that was the issue.

**Comment by natsnok** [comment]
I have the same issue. After a driver update, it worked for a while. Now it's broken again :/ 
Thanks fpr the advice to use a older version. I'm now also using V. 3.5.2019.1 and it works perfectly.

**Comment by Boerny41** [comment]
Had the problem a few months ago and going back to 3.5.2019.1 solved it. 
Yesterday I got Windows updates again, and even though my driver is still at version 3.5.2019.1 it is once again broken. Not sure what changed.

**Comment by duckstin** [comment]
Mine was working fine until the other day also, then it stopped working just like in this screenshot.

**Comment by Varga-Levente** [comment]
> Mine was working fine until the other day also, then it stopped working just like in this screenshot.

Just reinstall the older version of CH340

**Comment by natsnok** [comment]
> Had the problem a few months ago and going back to 3.5.2019.1 solved it. Yesterday I got Windows updates again, and even though my driver is still at version 3.5.2019.1 it is once again broken. Not sure what changed.

Same here. I started a new issue for this problem.
A temporary solution is to update to the current driver version (the non-working one) and then change back to version 3.5.2019.1.
This works but only for a short time, then Deej doesn't work anymore, and you need to do it again. Very frustrating.

**Comment by satsukiyatoshi** [comment]
The old driver is working for deej, but i had since random windows crash and seems to be caused by the older's driver's version (probably why microsoft's updated it)

![Image](https://github.com/user-attachments/assets/df41d291-b4e6-4a70-8f9a-44692c16e1a6)

so no more deej from me until it can work with up to date driver T_T

**Comment by CardinalFangIsHere** [comment]
This app needs an update, stat!
I haven't updated yet but for me it keeps stopping for no reason, restarting deej is the only thing that helps.

**Comment by satsukiyatoshi** [comment]
Summary :
Current driver version with windows update v3.9 : deej don't work
Old driver version 3.5 : deej works but random windows crashs
Old driver version 3.7 : deej works - just installed now, i let you know in some days/week if i get crash with this version too (could take some time to be sure as with 3.5 i got about 4/5 crash a month)

**Comment by florinremi** [comment]
Same here current driver 3.9 doesn't work with Deej.
3.5 => Bluescreen
3.7 => BlueScreen
I try now with 3.8 :) Fingers crossed !

**Comment by satsukiyatoshi** [comment]
I now use this version with offciial lastest windows (11) driver and didn't get a single crash since https://github.com/Skyfighter64/deej

**Comment by florinremi** [comment]
> I now use this version with offciial lastest windows (11) driver and didn't get a single crash since https://github.com/Skyfighter64/deej

Ho thank man !

**Comment by duckstin** [comment]
> I now use this version with offciial lastest windows (11) driver and didn't get a single crash since https://github.com/Skyfighter64/deej

Great find. Thanks!

**Comment by Varga-Levente** [comment]
> I now use this version with offciial lastest windows (11) driver and didn't get a single crash since https://github.com/Skyfighter64/deej

Can you send the link for the driver here?

**Comment by satsukiyatoshi** [comment]
> > I now use this version with offciial lastest windows (11) driver and didn't get a single crash since https://github.com/Skyfighter64/deej
> 
> Can you send the link for the driver here?

No specific link, just use windows device manager to update ^^

**Comment by Varga-Levente** [comment]
> > > I now use this version with offciial lastest windows (11) driver and didn't get a single crash since https://github.com/Skyfighter64/deej
> > 
> > Can you send the link for the driver here?
> 
> No specific link, just use windows device manager to update ^^

Thanks I will try it.

**Comment by michaelwschultz** [comment]
I've updated the project quite a bit and added a bunch of connection fixes. Give this build a shot and let me know if it works for you. #146
